apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-llama32-1b-instruct
  namespace: llama-instruct-32-1b-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${PVC_SIZE}
  storageClassName: ${STORAGE_CLASS}
